// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package network

import (
	"github.com/scaling-lightning/scaling-lightning/pkg/lightningnode"
	"github.com/scaling-lightning/scaling-lightning/pkg/standardclient/common"
	"github.com/scaling-lightning/scaling-lightning/pkg/standardclient/lightning"
	"github.com/scaling-lightning/scaling-lightning/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLightningNodeInterface creates a new instance of MockLightningNodeInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLightningNodeInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLightningNodeInterface {
	mock := &MockLightningNodeInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLightningNodeInterface is an autogenerated mock type for the LightningNodeInterface type
type MockLightningNodeInterface struct {
	mock.Mock
}

type MockLightningNodeInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLightningNodeInterface) EXPECT() *MockLightningNodeInterface_Expecter {
	return &MockLightningNodeInterface_Expecter{mock: &_m.Mock}
}

// ChannelBalance provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) ChannelBalance(client lightning.LightningClient) (types.Amount, error) {
	ret := _mock.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for ChannelBalance")
	}

	var r0 types.Amount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient) (types.Amount, error)); ok {
		return returnFunc(client)
	}
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient) types.Amount); ok {
		r0 = returnFunc(client)
	} else {
		r0 = ret.Get(0).(types.Amount)
	}
	if returnFunc, ok := ret.Get(1).(func(lightning.LightningClient) error); ok {
		r1 = returnFunc(client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLightningNodeInterface_ChannelBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChannelBalance'
type MockLightningNodeInterface_ChannelBalance_Call struct {
	*mock.Call
}

// ChannelBalance is a helper method to define mock.On call
//   - client lightning.LightningClient
func (_e *MockLightningNodeInterface_Expecter) ChannelBalance(client interface{}) *MockLightningNodeInterface_ChannelBalance_Call {
	return &MockLightningNodeInterface_ChannelBalance_Call{Call: _e.mock.On("ChannelBalance", client)}
}

func (_c *MockLightningNodeInterface_ChannelBalance_Call) Run(run func(client lightning.LightningClient)) *MockLightningNodeInterface_ChannelBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lightning.LightningClient
		if args[0] != nil {
			arg0 = args[0].(lightning.LightningClient)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_ChannelBalance_Call) Return(amount types.Amount, err error) *MockLightningNodeInterface_ChannelBalance_Call {
	_c.Call.Return(amount, err)
	return _c
}

func (_c *MockLightningNodeInterface_ChannelBalance_Call) RunAndReturn(run func(client lightning.LightningClient) (types.Amount, error)) *MockLightningNodeInterface_ChannelBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectPeer provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) ConnectPeer(client lightning.LightningClient, pubkey types.PubKey, nodeName string) error {
	ret := _mock.Called(client, pubkey, nodeName)

	if len(ret) == 0 {
		panic("no return value specified for ConnectPeer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient, types.PubKey, string) error); ok {
		r0 = returnFunc(client, pubkey, nodeName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLightningNodeInterface_ConnectPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectPeer'
type MockLightningNodeInterface_ConnectPeer_Call struct {
	*mock.Call
}

// ConnectPeer is a helper method to define mock.On call
//   - client lightning.LightningClient
//   - pubkey types.PubKey
//   - nodeName string
func (_e *MockLightningNodeInterface_Expecter) ConnectPeer(client interface{}, pubkey interface{}, nodeName interface{}) *MockLightningNodeInterface_ConnectPeer_Call {
	return &MockLightningNodeInterface_ConnectPeer_Call{Call: _e.mock.On("ConnectPeer", client, pubkey, nodeName)}
}

func (_c *MockLightningNodeInterface_ConnectPeer_Call) Run(run func(client lightning.LightningClient, pubkey types.PubKey, nodeName string)) *MockLightningNodeInterface_ConnectPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lightning.LightningClient
		if args[0] != nil {
			arg0 = args[0].(lightning.LightningClient)
		}
		var arg1 types.PubKey
		if args[1] != nil {
			arg1 = args[1].(types.PubKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_ConnectPeer_Call) Return(err error) *MockLightningNodeInterface_ConnectPeer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLightningNodeInterface_ConnectPeer_Call) RunAndReturn(run func(client lightning.LightningClient, pubkey types.PubKey, nodeName string) error) *MockLightningNodeInterface_ConnectPeer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvoice provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) CreateInvoice(client lightning.LightningClient, amountSats uint64) (string, error) {
	ret := _mock.Called(client, amountSats)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvoice")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient, uint64) (string, error)); ok {
		return returnFunc(client, amountSats)
	}
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient, uint64) string); ok {
		r0 = returnFunc(client, amountSats)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(lightning.LightningClient, uint64) error); ok {
		r1 = returnFunc(client, amountSats)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLightningNodeInterface_CreateInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvoice'
type MockLightningNodeInterface_CreateInvoice_Call struct {
	*mock.Call
}

// CreateInvoice is a helper method to define mock.On call
//   - client lightning.LightningClient
//   - amountSats uint64
func (_e *MockLightningNodeInterface_Expecter) CreateInvoice(client interface{}, amountSats interface{}) *MockLightningNodeInterface_CreateInvoice_Call {
	return &MockLightningNodeInterface_CreateInvoice_Call{Call: _e.mock.On("CreateInvoice", client, amountSats)}
}

func (_c *MockLightningNodeInterface_CreateInvoice_Call) Run(run func(client lightning.LightningClient, amountSats uint64)) *MockLightningNodeInterface_CreateInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lightning.LightningClient
		if args[0] != nil {
			arg0 = args[0].(lightning.LightningClient)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_CreateInvoice_Call) Return(s string, err error) *MockLightningNodeInterface_CreateInvoice_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLightningNodeInterface_CreateInvoice_Call) RunAndReturn(run func(client lightning.LightningClient, amountSats uint64) (string, error)) *MockLightningNodeInterface_CreateInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionFiles provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) GetConnectionFiles(network string, kubeConfig string) (*lightningnode.ConnectionFiles, error) {
	ret := _mock.Called(network, kubeConfig)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionFiles")
	}

	var r0 *lightningnode.ConnectionFiles
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*lightningnode.ConnectionFiles, error)); ok {
		return returnFunc(network, kubeConfig)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *lightningnode.ConnectionFiles); ok {
		r0 = returnFunc(network, kubeConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lightningnode.ConnectionFiles)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(network, kubeConfig)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLightningNodeInterface_GetConnectionFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionFiles'
type MockLightningNodeInterface_GetConnectionFiles_Call struct {
	*mock.Call
}

// GetConnectionFiles is a helper method to define mock.On call
//   - network string
//   - kubeConfig string
func (_e *MockLightningNodeInterface_Expecter) GetConnectionFiles(network interface{}, kubeConfig interface{}) *MockLightningNodeInterface_GetConnectionFiles_Call {
	return &MockLightningNodeInterface_GetConnectionFiles_Call{Call: _e.mock.On("GetConnectionFiles", network, kubeConfig)}
}

func (_c *MockLightningNodeInterface_GetConnectionFiles_Call) Run(run func(network string, kubeConfig string)) *MockLightningNodeInterface_GetConnectionFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_GetConnectionFiles_Call) Return(connectionFiles *lightningnode.ConnectionFiles, err error) *MockLightningNodeInterface_GetConnectionFiles_Call {
	_c.Call.Return(connectionFiles, err)
	return _c
}

func (_c *MockLightningNodeInterface_GetConnectionFiles_Call) RunAndReturn(run func(network string, kubeConfig string) (*lightningnode.ConnectionFiles, error)) *MockLightningNodeInterface_GetConnectionFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionPort provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) GetConnectionPort(kubeConfig string) (uint16, error) {
	ret := _mock.Called(kubeConfig)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionPort")
	}

	var r0 uint16
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (uint16, error)); ok {
		return returnFunc(kubeConfig)
	}
	if returnFunc, ok := ret.Get(0).(func(string) uint16); ok {
		r0 = returnFunc(kubeConfig)
	} else {
		r0 = ret.Get(0).(uint16)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(kubeConfig)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLightningNodeInterface_GetConnectionPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionPort'
type MockLightningNodeInterface_GetConnectionPort_Call struct {
	*mock.Call
}

// GetConnectionPort is a helper method to define mock.On call
//   - kubeConfig string
func (_e *MockLightningNodeInterface_Expecter) GetConnectionPort(kubeConfig interface{}) *MockLightningNodeInterface_GetConnectionPort_Call {
	return &MockLightningNodeInterface_GetConnectionPort_Call{Call: _e.mock.On("GetConnectionPort", kubeConfig)}
}

func (_c *MockLightningNodeInterface_GetConnectionPort_Call) Run(run func(kubeConfig string)) *MockLightningNodeInterface_GetConnectionPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_GetConnectionPort_Call) Return(v uint16, err error) *MockLightningNodeInterface_GetConnectionPort_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockLightningNodeInterface_GetConnectionPort_Call) RunAndReturn(run func(kubeConfig string) (uint16, error)) *MockLightningNodeInterface_GetConnectionPort_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockLightningNodeInterface_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockLightningNodeInterface_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockLightningNodeInterface_Expecter) GetName() *MockLightningNodeInterface_GetName_Call {
	return &MockLightningNodeInterface_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockLightningNodeInterface_GetName_Call) Run(run func()) *MockLightningNodeInterface_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLightningNodeInterface_GetName_Call) Return(s string) *MockLightningNodeInterface_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockLightningNodeInterface_GetName_Call) RunAndReturn(run func() string) *MockLightningNodeInterface_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewAddress provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) GetNewAddress(client common.CommonClient) (string, error) {
	ret := _mock.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for GetNewAddress")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(common.CommonClient) (string, error)); ok {
		return returnFunc(client)
	}
	if returnFunc, ok := ret.Get(0).(func(common.CommonClient) string); ok {
		r0 = returnFunc(client)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(common.CommonClient) error); ok {
		r1 = returnFunc(client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLightningNodeInterface_GetNewAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewAddress'
type MockLightningNodeInterface_GetNewAddress_Call struct {
	*mock.Call
}

// GetNewAddress is a helper method to define mock.On call
//   - client common.CommonClient
func (_e *MockLightningNodeInterface_Expecter) GetNewAddress(client interface{}) *MockLightningNodeInterface_GetNewAddress_Call {
	return &MockLightningNodeInterface_GetNewAddress_Call{Call: _e.mock.On("GetNewAddress", client)}
}

func (_c *MockLightningNodeInterface_GetNewAddress_Call) Run(run func(client common.CommonClient)) *MockLightningNodeInterface_GetNewAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 common.CommonClient
		if args[0] != nil {
			arg0 = args[0].(common.CommonClient)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_GetNewAddress_Call) Return(s string, err error) *MockLightningNodeInterface_GetNewAddress_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLightningNodeInterface_GetNewAddress_Call) RunAndReturn(run func(client common.CommonClient) (string, error)) *MockLightningNodeInterface_GetNewAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetPubKey provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) GetPubKey(client lightning.LightningClient) (types.PubKey, error) {
	ret := _mock.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for GetPubKey")
	}

	var r0 types.PubKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient) (types.PubKey, error)); ok {
		return returnFunc(client)
	}
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient) types.PubKey); ok {
		r0 = returnFunc(client)
	} else {
		r0 = ret.Get(0).(types.PubKey)
	}
	if returnFunc, ok := ret.Get(1).(func(lightning.LightningClient) error); ok {
		r1 = returnFunc(client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLightningNodeInterface_GetPubKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPubKey'
type MockLightningNodeInterface_GetPubKey_Call struct {
	*mock.Call
}

// GetPubKey is a helper method to define mock.On call
//   - client lightning.LightningClient
func (_e *MockLightningNodeInterface_Expecter) GetPubKey(client interface{}) *MockLightningNodeInterface_GetPubKey_Call {
	return &MockLightningNodeInterface_GetPubKey_Call{Call: _e.mock.On("GetPubKey", client)}
}

func (_c *MockLightningNodeInterface_GetPubKey_Call) Run(run func(client lightning.LightningClient)) *MockLightningNodeInterface_GetPubKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lightning.LightningClient
		if args[0] != nil {
			arg0 = args[0].(lightning.LightningClient)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_GetPubKey_Call) Return(pubKey types.PubKey, err error) *MockLightningNodeInterface_GetPubKey_Call {
	_c.Call.Return(pubKey, err)
	return _c
}

func (_c *MockLightningNodeInterface_GetPubKey_Call) RunAndReturn(run func(client lightning.LightningClient) (types.PubKey, error)) *MockLightningNodeInterface_GetPubKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletBalance provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) GetWalletBalance(client common.CommonClient) (types.Amount, error) {
	ret := _mock.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletBalance")
	}

	var r0 types.Amount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(common.CommonClient) (types.Amount, error)); ok {
		return returnFunc(client)
	}
	if returnFunc, ok := ret.Get(0).(func(common.CommonClient) types.Amount); ok {
		r0 = returnFunc(client)
	} else {
		r0 = ret.Get(0).(types.Amount)
	}
	if returnFunc, ok := ret.Get(1).(func(common.CommonClient) error); ok {
		r1 = returnFunc(client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLightningNodeInterface_GetWalletBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletBalance'
type MockLightningNodeInterface_GetWalletBalance_Call struct {
	*mock.Call
}

// GetWalletBalance is a helper method to define mock.On call
//   - client common.CommonClient
func (_e *MockLightningNodeInterface_Expecter) GetWalletBalance(client interface{}) *MockLightningNodeInterface_GetWalletBalance_Call {
	return &MockLightningNodeInterface_GetWalletBalance_Call{Call: _e.mock.On("GetWalletBalance", client)}
}

func (_c *MockLightningNodeInterface_GetWalletBalance_Call) Run(run func(client common.CommonClient)) *MockLightningNodeInterface_GetWalletBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 common.CommonClient
		if args[0] != nil {
			arg0 = args[0].(common.CommonClient)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_GetWalletBalance_Call) Return(amount types.Amount, err error) *MockLightningNodeInterface_GetWalletBalance_Call {
	_c.Call.Return(amount, err)
	return _c
}

func (_c *MockLightningNodeInterface_GetWalletBalance_Call) RunAndReturn(run func(client common.CommonClient) (types.Amount, error)) *MockLightningNodeInterface_GetWalletBalance_Call {
	_c.Call.Return(run)
	return _c
}

// OpenChannel provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) OpenChannel(client lightning.LightningClient, pubkey types.PubKey, localAmt types.Amount) (types.ChannelPoint, error) {
	ret := _mock.Called(client, pubkey, localAmt)

	if len(ret) == 0 {
		panic("no return value specified for OpenChannel")
	}

	var r0 types.ChannelPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient, types.PubKey, types.Amount) (types.ChannelPoint, error)); ok {
		return returnFunc(client, pubkey, localAmt)
	}
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient, types.PubKey, types.Amount) types.ChannelPoint); ok {
		r0 = returnFunc(client, pubkey, localAmt)
	} else {
		r0 = ret.Get(0).(types.ChannelPoint)
	}
	if returnFunc, ok := ret.Get(1).(func(lightning.LightningClient, types.PubKey, types.Amount) error); ok {
		r1 = returnFunc(client, pubkey, localAmt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLightningNodeInterface_OpenChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenChannel'
type MockLightningNodeInterface_OpenChannel_Call struct {
	*mock.Call
}

// OpenChannel is a helper method to define mock.On call
//   - client lightning.LightningClient
//   - pubkey types.PubKey
//   - localAmt types.Amount
func (_e *MockLightningNodeInterface_Expecter) OpenChannel(client interface{}, pubkey interface{}, localAmt interface{}) *MockLightningNodeInterface_OpenChannel_Call {
	return &MockLightningNodeInterface_OpenChannel_Call{Call: _e.mock.On("OpenChannel", client, pubkey, localAmt)}
}

func (_c *MockLightningNodeInterface_OpenChannel_Call) Run(run func(client lightning.LightningClient, pubkey types.PubKey, localAmt types.Amount)) *MockLightningNodeInterface_OpenChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lightning.LightningClient
		if args[0] != nil {
			arg0 = args[0].(lightning.LightningClient)
		}
		var arg1 types.PubKey
		if args[1] != nil {
			arg1 = args[1].(types.PubKey)
		}
		var arg2 types.Amount
		if args[2] != nil {
			arg2 = args[2].(types.Amount)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_OpenChannel_Call) Return(channelPoint types.ChannelPoint, err error) *MockLightningNodeInterface_OpenChannel_Call {
	_c.Call.Return(channelPoint, err)
	return _c
}

func (_c *MockLightningNodeInterface_OpenChannel_Call) RunAndReturn(run func(client lightning.LightningClient, pubkey types.PubKey, localAmt types.Amount) (types.ChannelPoint, error)) *MockLightningNodeInterface_OpenChannel_Call {
	_c.Call.Return(run)
	return _c
}

// PayInvoice provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) PayInvoice(client lightning.LightningClient, invoice string) (string, error) {
	ret := _mock.Called(client, invoice)

	if len(ret) == 0 {
		panic("no return value specified for PayInvoice")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient, string) (string, error)); ok {
		return returnFunc(client, invoice)
	}
	if returnFunc, ok := ret.Get(0).(func(lightning.LightningClient, string) string); ok {
		r0 = returnFunc(client, invoice)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(lightning.LightningClient, string) error); ok {
		r1 = returnFunc(client, invoice)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLightningNodeInterface_PayInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayInvoice'
type MockLightningNodeInterface_PayInvoice_Call struct {
	*mock.Call
}

// PayInvoice is a helper method to define mock.On call
//   - client lightning.LightningClient
//   - invoice string
func (_e *MockLightningNodeInterface_Expecter) PayInvoice(client interface{}, invoice interface{}) *MockLightningNodeInterface_PayInvoice_Call {
	return &MockLightningNodeInterface_PayInvoice_Call{Call: _e.mock.On("PayInvoice", client, invoice)}
}

func (_c *MockLightningNodeInterface_PayInvoice_Call) Run(run func(client lightning.LightningClient, invoice string)) *MockLightningNodeInterface_PayInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lightning.LightningClient
		if args[0] != nil {
			arg0 = args[0].(lightning.LightningClient)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_PayInvoice_Call) Return(s string, err error) *MockLightningNodeInterface_PayInvoice_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLightningNodeInterface_PayInvoice_Call) RunAndReturn(run func(client lightning.LightningClient, invoice string) (string, error)) *MockLightningNodeInterface_PayInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// SendToAddress provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) SendToAddress(client common.CommonClient, address string, amount types.Amount) (string, error) {
	ret := _mock.Called(client, address, amount)

	if len(ret) == 0 {
		panic("no return value specified for SendToAddress")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(common.CommonClient, string, types.Amount) (string, error)); ok {
		return returnFunc(client, address, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(common.CommonClient, string, types.Amount) string); ok {
		r0 = returnFunc(client, address, amount)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(common.CommonClient, string, types.Amount) error); ok {
		r1 = returnFunc(client, address, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLightningNodeInterface_SendToAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendToAddress'
type MockLightningNodeInterface_SendToAddress_Call struct {
	*mock.Call
}

// SendToAddress is a helper method to define mock.On call
//   - client common.CommonClient
//   - address string
//   - amount types.Amount
func (_e *MockLightningNodeInterface_Expecter) SendToAddress(client interface{}, address interface{}, amount interface{}) *MockLightningNodeInterface_SendToAddress_Call {
	return &MockLightningNodeInterface_SendToAddress_Call{Call: _e.mock.On("SendToAddress", client, address, amount)}
}

func (_c *MockLightningNodeInterface_SendToAddress_Call) Run(run func(client common.CommonClient, address string, amount types.Amount)) *MockLightningNodeInterface_SendToAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 common.CommonClient
		if args[0] != nil {
			arg0 = args[0].(common.CommonClient)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Amount
		if args[2] != nil {
			arg2 = args[2].(types.Amount)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_SendToAddress_Call) Return(s string, err error) *MockLightningNodeInterface_SendToAddress_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLightningNodeInterface_SendToAddress_Call) RunAndReturn(run func(client common.CommonClient, address string, amount types.Amount) (string, error)) *MockLightningNodeInterface_SendToAddress_Call {
	_c.Call.Return(run)
	return _c
}

// WriteAuthFilesToDirectory provides a mock function for the type MockLightningNodeInterface
func (_mock *MockLightningNodeInterface) WriteAuthFilesToDirectory(network string, kubeConfig string, dir string) error {
	ret := _mock.Called(network, kubeConfig, dir)

	if len(ret) == 0 {
		panic("no return value specified for WriteAuthFilesToDirectory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(network, kubeConfig, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLightningNodeInterface_WriteAuthFilesToDirectory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAuthFilesToDirectory'
type MockLightningNodeInterface_WriteAuthFilesToDirectory_Call struct {
	*mock.Call
}

// WriteAuthFilesToDirectory is a helper method to define mock.On call
//   - network string
//   - kubeConfig string
//   - dir string
func (_e *MockLightningNodeInterface_Expecter) WriteAuthFilesToDirectory(network interface{}, kubeConfig interface{}, dir interface{}) *MockLightningNodeInterface_WriteAuthFilesToDirectory_Call {
	return &MockLightningNodeInterface_WriteAuthFilesToDirectory_Call{Call: _e.mock.On("WriteAuthFilesToDirectory", network, kubeConfig, dir)}
}

func (_c *MockLightningNodeInterface_WriteAuthFilesToDirectory_Call) Run(run func(network string, kubeConfig string, dir string)) *MockLightningNodeInterface_WriteAuthFilesToDirectory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLightningNodeInterface_WriteAuthFilesToDirectory_Call) Return(err error) *MockLightningNodeInterface_WriteAuthFilesToDirectory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLightningNodeInterface_WriteAuthFilesToDirectory_Call) RunAndReturn(run func(network string, kubeConfig string, dir string) error) *MockLightningNodeInterface_WriteAuthFilesToDirectory_Call {
	_c.Call.Return(run)
	return _c
}
