// Code generated by mockery v2.34.2. DO NOT EDIT.

package bitcoin

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockBitcoinClient is an autogenerated mock type for the BitcoinClient type
type MockBitcoinClient struct {
	mock.Mock
}

type MockBitcoinClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBitcoinClient) EXPECT() *MockBitcoinClient_Expecter {
	return &MockBitcoinClient_Expecter{mock: &_m.Mock}
}

// GenerateToAddress provides a mock function with given fields: ctx, in, opts
func (_m *MockBitcoinClient) GenerateToAddress(ctx context.Context, in *GenerateToAddressRequest, opts ...grpc.CallOption) (*GenerateToAddressResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *GenerateToAddressResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GenerateToAddressRequest, ...grpc.CallOption) (*GenerateToAddressResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GenerateToAddressRequest, ...grpc.CallOption) *GenerateToAddressResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GenerateToAddressResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GenerateToAddressRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBitcoinClient_GenerateToAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToAddress'
type MockBitcoinClient_GenerateToAddress_Call struct {
	*mock.Call
}

// GenerateToAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - in *GenerateToAddressRequest
//   - opts ...grpc.CallOption
func (_e *MockBitcoinClient_Expecter) GenerateToAddress(ctx interface{}, in interface{}, opts ...interface{}) *MockBitcoinClient_GenerateToAddress_Call {
	return &MockBitcoinClient_GenerateToAddress_Call{Call: _e.mock.On("GenerateToAddress",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockBitcoinClient_GenerateToAddress_Call) Run(run func(ctx context.Context, in *GenerateToAddressRequest, opts ...grpc.CallOption)) *MockBitcoinClient_GenerateToAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*GenerateToAddressRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockBitcoinClient_GenerateToAddress_Call) Return(_a0 *GenerateToAddressResponse, _a1 error) *MockBitcoinClient_GenerateToAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBitcoinClient_GenerateToAddress_Call) RunAndReturn(run func(context.Context, *GenerateToAddressRequest, ...grpc.CallOption) (*GenerateToAddressResponse, error)) *MockBitcoinClient_GenerateToAddress_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBitcoinClient creates a new instance of MockBitcoinClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBitcoinClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBitcoinClient {
	mock := &MockBitcoinClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
