// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bitcoin

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockBitcoinClient creates a new instance of MockBitcoinClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBitcoinClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBitcoinClient {
	mock := &MockBitcoinClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBitcoinClient is an autogenerated mock type for the BitcoinClient type
type MockBitcoinClient struct {
	mock.Mock
}

type MockBitcoinClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBitcoinClient) EXPECT() *MockBitcoinClient_Expecter {
	return &MockBitcoinClient_Expecter{mock: &_m.Mock}
}

// GenerateToAddress provides a mock function for the type MockBitcoinClient
func (_mock *MockBitcoinClient) GenerateToAddress(ctx context.Context, in *GenerateToAddressRequest, opts ...grpc.CallOption) (*GenerateToAddressResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToAddress")
	}

	var r0 *GenerateToAddressResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GenerateToAddressRequest, ...grpc.CallOption) (*GenerateToAddressResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GenerateToAddressRequest, ...grpc.CallOption) *GenerateToAddressResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GenerateToAddressResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *GenerateToAddressRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBitcoinClient_GenerateToAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToAddress'
type MockBitcoinClient_GenerateToAddress_Call struct {
	*mock.Call
}

// GenerateToAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - in *GenerateToAddressRequest
//   - opts ...grpc.CallOption
func (_e *MockBitcoinClient_Expecter) GenerateToAddress(ctx interface{}, in interface{}, opts ...interface{}) *MockBitcoinClient_GenerateToAddress_Call {
	return &MockBitcoinClient_GenerateToAddress_Call{Call: _e.mock.On("GenerateToAddress",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockBitcoinClient_GenerateToAddress_Call) Run(run func(ctx context.Context, in *GenerateToAddressRequest, opts ...grpc.CallOption)) *MockBitcoinClient_GenerateToAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *GenerateToAddressRequest
		if args[1] != nil {
			arg1 = args[1].(*GenerateToAddressRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockBitcoinClient_GenerateToAddress_Call) Return(generateToAddressResponse *GenerateToAddressResponse, err error) *MockBitcoinClient_GenerateToAddress_Call {
	_c.Call.Return(generateToAddressResponse, err)
	return _c
}

func (_c *MockBitcoinClient_GenerateToAddress_Call) RunAndReturn(run func(ctx context.Context, in *GenerateToAddressRequest, opts ...grpc.CallOption) (*GenerateToAddressResponse, error)) *MockBitcoinClient_GenerateToAddress_Call {
	_c.Call.Return(run)
	return _c
}
