// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.6
// source: common_client.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletBalanceRequest) Reset() {
	*x = WalletBalanceRequest{}
	mi := &file_common_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletBalanceRequest) ProtoMessage() {}

func (x *WalletBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletBalanceRequest.ProtoReflect.Descriptor instead.
func (*WalletBalanceRequest) Descriptor() ([]byte, []int) {
	return file_common_client_proto_rawDescGZIP(), []int{0}
}

type WalletBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalanceSats   uint64                 `protobuf:"varint,1,opt,name=balanceSats,proto3" json:"balanceSats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletBalanceResponse) Reset() {
	*x = WalletBalanceResponse{}
	mi := &file_common_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletBalanceResponse) ProtoMessage() {}

func (x *WalletBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletBalanceResponse.ProtoReflect.Descriptor instead.
func (*WalletBalanceResponse) Descriptor() ([]byte, []int) {
	return file_common_client_proto_rawDescGZIP(), []int{1}
}

func (x *WalletBalanceResponse) GetBalanceSats() uint64 {
	if x != nil {
		return x.BalanceSats
	}
	return 0
}

type NewAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAddressRequest) Reset() {
	*x = NewAddressRequest{}
	mi := &file_common_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressRequest) ProtoMessage() {}

func (x *NewAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressRequest.ProtoReflect.Descriptor instead.
func (*NewAddressRequest) Descriptor() ([]byte, []int) {
	return file_common_client_proto_rawDescGZIP(), []int{2}
}

type NewAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAddressResponse) Reset() {
	*x = NewAddressResponse{}
	mi := &file_common_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressResponse) ProtoMessage() {}

func (x *NewAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressResponse.ProtoReflect.Descriptor instead.
func (*NewAddressResponse) Descriptor() ([]byte, []int) {
	return file_common_client_proto_rawDescGZIP(), []int{3}
}

func (x *NewAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_common_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_common_client_proto_rawDescGZIP(), []int{4}
}

func (x *SendRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SendRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_common_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_common_client_proto_rawDescGZIP(), []int{5}
}

func (x *SendResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

var File_common_client_proto protoreflect.FileDescriptor

const file_common_client_proto_rawDesc = "" +
	"\n" +
	"\x13common_client.proto\"\x16\n" +
	"\x14WalletBalanceRequest\"9\n" +
	"\x15WalletBalanceResponse\x12 \n" +
	"\vbalanceSats\x18\x01 \x01(\x04R\vbalanceSats\"\x13\n" +
	"\x11NewAddressRequest\".\n" +
	"\x12NewAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"?\n" +
	"\vSendRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"\"\n" +
	"\fSendResponse\x12\x12\n" +
	"\x04txId\x18\x01 \x01(\tR\x04txId2\xaa\x01\n" +
	"\x06Common\x12@\n" +
	"\rWalletBalance\x12\x15.WalletBalanceRequest\x1a\x16.WalletBalanceResponse\"\x00\x127\n" +
	"\n" +
	"NewAddress\x12\x12.NewAddressRequest\x1a\x13.NewAddressResponse\"\x00\x12%\n" +
	"\x04Send\x12\f.SendRequest\x1a\r.SendResponse\"\x00b\x06proto3"

var (
	file_common_client_proto_rawDescOnce sync.Once
	file_common_client_proto_rawDescData []byte
)

func file_common_client_proto_rawDescGZIP() []byte {
	file_common_client_proto_rawDescOnce.Do(func() {
		file_common_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_client_proto_rawDesc), len(file_common_client_proto_rawDesc)))
	})
	return file_common_client_proto_rawDescData
}

var file_common_client_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_client_proto_goTypes = []any{
	(*WalletBalanceRequest)(nil),  // 0: WalletBalanceRequest
	(*WalletBalanceResponse)(nil), // 1: WalletBalanceResponse
	(*NewAddressRequest)(nil),     // 2: NewAddressRequest
	(*NewAddressResponse)(nil),    // 3: NewAddressResponse
	(*SendRequest)(nil),           // 4: SendRequest
	(*SendResponse)(nil),          // 5: SendResponse
}
var file_common_client_proto_depIdxs = []int32{
	0, // 0: Common.WalletBalance:input_type -> WalletBalanceRequest
	2, // 1: Common.NewAddress:input_type -> NewAddressRequest
	4, // 2: Common.Send:input_type -> SendRequest
	1, // 3: Common.WalletBalance:output_type -> WalletBalanceResponse
	3, // 4: Common.NewAddress:output_type -> NewAddressResponse
	5, // 5: Common.Send:output_type -> SendResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_client_proto_init() }
func file_common_client_proto_init() {
	if File_common_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_client_proto_rawDesc), len(file_common_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_client_proto_goTypes,
		DependencyIndexes: file_common_client_proto_depIdxs,
		MessageInfos:      file_common_client_proto_msgTypes,
	}.Build()
	File_common_client_proto = out.File
	file_common_client_proto_goTypes = nil
	file_common_client_proto_depIdxs = nil
}
