// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package common

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockCommonClient creates a new instance of MockCommonClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommonClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommonClient {
	mock := &MockCommonClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommonClient is an autogenerated mock type for the CommonClient type
type MockCommonClient struct {
	mock.Mock
}

type MockCommonClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommonClient) EXPECT() *MockCommonClient_Expecter {
	return &MockCommonClient_Expecter{mock: &_m.Mock}
}

// NewAddress provides a mock function for the type MockCommonClient
func (_mock *MockCommonClient) NewAddress(ctx context.Context, in *NewAddressRequest, opts ...grpc.CallOption) (*NewAddressResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for NewAddress")
	}

	var r0 *NewAddressResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *NewAddressRequest, ...grpc.CallOption) (*NewAddressResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *NewAddressRequest, ...grpc.CallOption) *NewAddressResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NewAddressResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *NewAddressRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonClient_NewAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAddress'
type MockCommonClient_NewAddress_Call struct {
	*mock.Call
}

// NewAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - in *NewAddressRequest
//   - opts ...grpc.CallOption
func (_e *MockCommonClient_Expecter) NewAddress(ctx interface{}, in interface{}, opts ...interface{}) *MockCommonClient_NewAddress_Call {
	return &MockCommonClient_NewAddress_Call{Call: _e.mock.On("NewAddress",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCommonClient_NewAddress_Call) Run(run func(ctx context.Context, in *NewAddressRequest, opts ...grpc.CallOption)) *MockCommonClient_NewAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *NewAddressRequest
		if args[1] != nil {
			arg1 = args[1].(*NewAddressRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommonClient_NewAddress_Call) Return(newAddressResponse *NewAddressResponse, err error) *MockCommonClient_NewAddress_Call {
	_c.Call.Return(newAddressResponse, err)
	return _c
}

func (_c *MockCommonClient_NewAddress_Call) RunAndReturn(run func(ctx context.Context, in *NewAddressRequest, opts ...grpc.CallOption) (*NewAddressResponse, error)) *MockCommonClient_NewAddress_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockCommonClient
func (_mock *MockCommonClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 *SendResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SendRequest, ...grpc.CallOption) (*SendResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SendRequest, ...grpc.CallOption) *SendResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SendResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *SendRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockCommonClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - in *SendRequest
//   - opts ...grpc.CallOption
func (_e *MockCommonClient_Expecter) Send(ctx interface{}, in interface{}, opts ...interface{}) *MockCommonClient_Send_Call {
	return &MockCommonClient_Send_Call{Call: _e.mock.On("Send",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCommonClient_Send_Call) Run(run func(ctx context.Context, in *SendRequest, opts ...grpc.CallOption)) *MockCommonClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *SendRequest
		if args[1] != nil {
			arg1 = args[1].(*SendRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommonClient_Send_Call) Return(sendResponse *SendResponse, err error) *MockCommonClient_Send_Call {
	_c.Call.Return(sendResponse, err)
	return _c
}

func (_c *MockCommonClient_Send_Call) RunAndReturn(run func(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)) *MockCommonClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// WalletBalance provides a mock function for the type MockCommonClient
func (_mock *MockCommonClient) WalletBalance(ctx context.Context, in *WalletBalanceRequest, opts ...grpc.CallOption) (*WalletBalanceResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WalletBalance")
	}

	var r0 *WalletBalanceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *WalletBalanceRequest, ...grpc.CallOption) (*WalletBalanceResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *WalletBalanceRequest, ...grpc.CallOption) *WalletBalanceResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*WalletBalanceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *WalletBalanceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonClient_WalletBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalletBalance'
type MockCommonClient_WalletBalance_Call struct {
	*mock.Call
}

// WalletBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - in *WalletBalanceRequest
//   - opts ...grpc.CallOption
func (_e *MockCommonClient_Expecter) WalletBalance(ctx interface{}, in interface{}, opts ...interface{}) *MockCommonClient_WalletBalance_Call {
	return &MockCommonClient_WalletBalance_Call{Call: _e.mock.On("WalletBalance",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCommonClient_WalletBalance_Call) Run(run func(ctx context.Context, in *WalletBalanceRequest, opts ...grpc.CallOption)) *MockCommonClient_WalletBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *WalletBalanceRequest
		if args[1] != nil {
			arg1 = args[1].(*WalletBalanceRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommonClient_WalletBalance_Call) Return(walletBalanceResponse *WalletBalanceResponse, err error) *MockCommonClient_WalletBalance_Call {
	_c.Call.Return(walletBalanceResponse, err)
	return _c
}

func (_c *MockCommonClient_WalletBalance_Call) RunAndReturn(run func(ctx context.Context, in *WalletBalanceRequest, opts ...grpc.CallOption) (*WalletBalanceResponse, error)) *MockCommonClient_WalletBalance_Call {
	_c.Call.Return(run)
	return _c
}
