// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package initialstate

import (
	"github.com/scaling-lightning/scaling-lightning/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSLNetworkInterface creates a new instance of MockSLNetworkInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSLNetworkInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSLNetworkInterface {
	mock := &MockSLNetworkInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSLNetworkInterface is an autogenerated mock type for the SLNetworkInterface type
type MockSLNetworkInterface struct {
	mock.Mock
}

type MockSLNetworkInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSLNetworkInterface) EXPECT() *MockSLNetworkInterface_Expecter {
	return &MockSLNetworkInterface_Expecter{mock: &_m.Mock}
}

// ChannelBalance provides a mock function for the type MockSLNetworkInterface
func (_mock *MockSLNetworkInterface) ChannelBalance(nodeName string) (types.Amount, error) {
	ret := _mock.Called(nodeName)

	if len(ret) == 0 {
		panic("no return value specified for ChannelBalance")
	}

	var r0 types.Amount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.Amount, error)); ok {
		return returnFunc(nodeName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.Amount); ok {
		r0 = returnFunc(nodeName)
	} else {
		r0 = ret.Get(0).(types.Amount)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(nodeName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSLNetworkInterface_ChannelBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChannelBalance'
type MockSLNetworkInterface_ChannelBalance_Call struct {
	*mock.Call
}

// ChannelBalance is a helper method to define mock.On call
//   - nodeName string
func (_e *MockSLNetworkInterface_Expecter) ChannelBalance(nodeName interface{}) *MockSLNetworkInterface_ChannelBalance_Call {
	return &MockSLNetworkInterface_ChannelBalance_Call{Call: _e.mock.On("ChannelBalance", nodeName)}
}

func (_c *MockSLNetworkInterface_ChannelBalance_Call) Run(run func(nodeName string)) *MockSLNetworkInterface_ChannelBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSLNetworkInterface_ChannelBalance_Call) Return(amount types.Amount, err error) *MockSLNetworkInterface_ChannelBalance_Call {
	_c.Call.Return(amount, err)
	return _c
}

func (_c *MockSLNetworkInterface_ChannelBalance_Call) RunAndReturn(run func(nodeName string) (types.Amount, error)) *MockSLNetworkInterface_ChannelBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectPeer provides a mock function for the type MockSLNetworkInterface
func (_mock *MockSLNetworkInterface) ConnectPeer(fromNodeName string, toNodeName string) (string, error) {
	ret := _mock.Called(fromNodeName, toNodeName)

	if len(ret) == 0 {
		panic("no return value specified for ConnectPeer")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(fromNodeName, toNodeName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(fromNodeName, toNodeName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(fromNodeName, toNodeName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSLNetworkInterface_ConnectPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectPeer'
type MockSLNetworkInterface_ConnectPeer_Call struct {
	*mock.Call
}

// ConnectPeer is a helper method to define mock.On call
//   - fromNodeName string
//   - toNodeName string
func (_e *MockSLNetworkInterface_Expecter) ConnectPeer(fromNodeName interface{}, toNodeName interface{}) *MockSLNetworkInterface_ConnectPeer_Call {
	return &MockSLNetworkInterface_ConnectPeer_Call{Call: _e.mock.On("ConnectPeer", fromNodeName, toNodeName)}
}

func (_c *MockSLNetworkInterface_ConnectPeer_Call) Run(run func(fromNodeName string, toNodeName string)) *MockSLNetworkInterface_ConnectPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSLNetworkInterface_ConnectPeer_Call) Return(s string, err error) *MockSLNetworkInterface_ConnectPeer_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSLNetworkInterface_ConnectPeer_Call) RunAndReturn(run func(fromNodeName string, toNodeName string) (string, error)) *MockSLNetworkInterface_ConnectPeer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvoice provides a mock function for the type MockSLNetworkInterface
func (_mock *MockSLNetworkInterface) CreateInvoice(nodeName string, amountSats uint64) (string, error) {
	ret := _mock.Called(nodeName, amountSats)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvoice")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, uint64) (string, error)); ok {
		return returnFunc(nodeName, amountSats)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint64) string); ok {
		r0 = returnFunc(nodeName, amountSats)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint64) error); ok {
		r1 = returnFunc(nodeName, amountSats)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSLNetworkInterface_CreateInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvoice'
type MockSLNetworkInterface_CreateInvoice_Call struct {
	*mock.Call
}

// CreateInvoice is a helper method to define mock.On call
//   - nodeName string
//   - amountSats uint64
func (_e *MockSLNetworkInterface_Expecter) CreateInvoice(nodeName interface{}, amountSats interface{}) *MockSLNetworkInterface_CreateInvoice_Call {
	return &MockSLNetworkInterface_CreateInvoice_Call{Call: _e.mock.On("CreateInvoice", nodeName, amountSats)}
}

func (_c *MockSLNetworkInterface_CreateInvoice_Call) Run(run func(nodeName string, amountSats uint64)) *MockSLNetworkInterface_CreateInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSLNetworkInterface_CreateInvoice_Call) Return(s string, err error) *MockSLNetworkInterface_CreateInvoice_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSLNetworkInterface_CreateInvoice_Call) RunAndReturn(run func(nodeName string, amountSats uint64) (string, error)) *MockSLNetworkInterface_CreateInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// OpenChannel provides a mock function for the type MockSLNetworkInterface
func (_mock *MockSLNetworkInterface) OpenChannel(fromNodeName string, toNodeName string, localAmt uint64) (types.ChannelPoint, error) {
	ret := _mock.Called(fromNodeName, toNodeName, localAmt)

	if len(ret) == 0 {
		panic("no return value specified for OpenChannel")
	}

	var r0 types.ChannelPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, uint64) (types.ChannelPoint, error)); ok {
		return returnFunc(fromNodeName, toNodeName, localAmt)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, uint64) types.ChannelPoint); ok {
		r0 = returnFunc(fromNodeName, toNodeName, localAmt)
	} else {
		r0 = ret.Get(0).(types.ChannelPoint)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, uint64) error); ok {
		r1 = returnFunc(fromNodeName, toNodeName, localAmt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSLNetworkInterface_OpenChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenChannel'
type MockSLNetworkInterface_OpenChannel_Call struct {
	*mock.Call
}

// OpenChannel is a helper method to define mock.On call
//   - fromNodeName string
//   - toNodeName string
//   - localAmt uint64
func (_e *MockSLNetworkInterface_Expecter) OpenChannel(fromNodeName interface{}, toNodeName interface{}, localAmt interface{}) *MockSLNetworkInterface_OpenChannel_Call {
	return &MockSLNetworkInterface_OpenChannel_Call{Call: _e.mock.On("OpenChannel", fromNodeName, toNodeName, localAmt)}
}

func (_c *MockSLNetworkInterface_OpenChannel_Call) Run(run func(fromNodeName string, toNodeName string, localAmt uint64)) *MockSLNetworkInterface_OpenChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSLNetworkInterface_OpenChannel_Call) Return(channelPoint types.ChannelPoint, err error) *MockSLNetworkInterface_OpenChannel_Call {
	_c.Call.Return(channelPoint, err)
	return _c
}

func (_c *MockSLNetworkInterface_OpenChannel_Call) RunAndReturn(run func(fromNodeName string, toNodeName string, localAmt uint64) (types.ChannelPoint, error)) *MockSLNetworkInterface_OpenChannel_Call {
	_c.Call.Return(run)
	return _c
}

// PayInvoice provides a mock function for the type MockSLNetworkInterface
func (_mock *MockSLNetworkInterface) PayInvoice(nodeName string, invoice string) (string, error) {
	ret := _mock.Called(nodeName, invoice)

	if len(ret) == 0 {
		panic("no return value specified for PayInvoice")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(nodeName, invoice)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(nodeName, invoice)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(nodeName, invoice)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSLNetworkInterface_PayInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayInvoice'
type MockSLNetworkInterface_PayInvoice_Call struct {
	*mock.Call
}

// PayInvoice is a helper method to define mock.On call
//   - nodeName string
//   - invoice string
func (_e *MockSLNetworkInterface_Expecter) PayInvoice(nodeName interface{}, invoice interface{}) *MockSLNetworkInterface_PayInvoice_Call {
	return &MockSLNetworkInterface_PayInvoice_Call{Call: _e.mock.On("PayInvoice", nodeName, invoice)}
}

func (_c *MockSLNetworkInterface_PayInvoice_Call) Run(run func(nodeName string, invoice string)) *MockSLNetworkInterface_PayInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSLNetworkInterface_PayInvoice_Call) Return(s string, err error) *MockSLNetworkInterface_PayInvoice_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSLNetworkInterface_PayInvoice_Call) RunAndReturn(run func(nodeName string, invoice string) (string, error)) *MockSLNetworkInterface_PayInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockSLNetworkInterface
func (_mock *MockSLNetworkInterface) Send(fromNodeName string, toNodeName string, amountSats uint64) (string, error) {
	ret := _mock.Called(fromNodeName, toNodeName, amountSats)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, uint64) (string, error)); ok {
		return returnFunc(fromNodeName, toNodeName, amountSats)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, uint64) string); ok {
		r0 = returnFunc(fromNodeName, toNodeName, amountSats)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, uint64) error); ok {
		r1 = returnFunc(fromNodeName, toNodeName, amountSats)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSLNetworkInterface_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSLNetworkInterface_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - fromNodeName string
//   - toNodeName string
//   - amountSats uint64
func (_e *MockSLNetworkInterface_Expecter) Send(fromNodeName interface{}, toNodeName interface{}, amountSats interface{}) *MockSLNetworkInterface_Send_Call {
	return &MockSLNetworkInterface_Send_Call{Call: _e.mock.On("Send", fromNodeName, toNodeName, amountSats)}
}

func (_c *MockSLNetworkInterface_Send_Call) Run(run func(fromNodeName string, toNodeName string, amountSats uint64)) *MockSLNetworkInterface_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSLNetworkInterface_Send_Call) Return(s string, err error) *MockSLNetworkInterface_Send_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSLNetworkInterface_Send_Call) RunAndReturn(run func(fromNodeName string, toNodeName string, amountSats uint64) (string, error)) *MockSLNetworkInterface_Send_Call {
	_c.Call.Return(run)
	return _c
}
