// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.6
// source: lightning_client.proto

package lightning

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubKeyRequest) Reset() {
	*x = PubKeyRequest{}
	mi := &file_lightning_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKeyRequest) ProtoMessage() {}

func (x *PubKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKeyRequest.ProtoReflect.Descriptor instead.
func (*PubKeyRequest) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{0}
}

type PubKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        []byte                 `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubKeyResponse) Reset() {
	*x = PubKeyResponse{}
	mi := &file_lightning_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKeyResponse) ProtoMessage() {}

func (x *PubKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKeyResponse.ProtoReflect.Descriptor instead.
func (*PubKeyResponse) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{1}
}

func (x *PubKeyResponse) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

type ConnectPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        []byte                 `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeerRequest) Reset() {
	*x = ConnectPeerRequest{}
	mi := &file_lightning_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeerRequest) ProtoMessage() {}

func (x *ConnectPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeerRequest.ProtoReflect.Descriptor instead.
func (*ConnectPeerRequest) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectPeerRequest) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *ConnectPeerRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectPeerRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ConnectPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeerResponse) Reset() {
	*x = ConnectPeerResponse{}
	mi := &file_lightning_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeerResponse) ProtoMessage() {}

func (x *ConnectPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeerResponse.ProtoReflect.Descriptor instead.
func (*ConnectPeerResponse) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{3}
}

type OpenChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        []byte                 `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	LocalAmtSats  uint64                 `protobuf:"varint,2,opt,name=localAmtSats,proto3" json:"localAmtSats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenChannelRequest) Reset() {
	*x = OpenChannelRequest{}
	mi := &file_lightning_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelRequest) ProtoMessage() {}

func (x *OpenChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelRequest.ProtoReflect.Descriptor instead.
func (*OpenChannelRequest) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{4}
}

func (x *OpenChannelRequest) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *OpenChannelRequest) GetLocalAmtSats() uint64 {
	if x != nil {
		return x.LocalAmtSats
	}
	return 0
}

type OpenChannelResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FundingTxId          []byte                 `protobuf:"bytes,1,opt,name=fundingTxId,proto3" json:"fundingTxId,omitempty"`
	FundingTxOutputIndex uint32                 `protobuf:"varint,2,opt,name=fundingTxOutputIndex,proto3" json:"fundingTxOutputIndex,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OpenChannelResponse) Reset() {
	*x = OpenChannelResponse{}
	mi := &file_lightning_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelResponse) ProtoMessage() {}

func (x *OpenChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelResponse.ProtoReflect.Descriptor instead.
func (*OpenChannelResponse) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{5}
}

func (x *OpenChannelResponse) GetFundingTxId() []byte {
	if x != nil {
		return x.FundingTxId
	}
	return nil
}

func (x *OpenChannelResponse) GetFundingTxOutputIndex() uint32 {
	if x != nil {
		return x.FundingTxOutputIndex
	}
	return 0
}

type CreateInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmtSats       uint64                 `protobuf:"varint,1,opt,name=amtSats,proto3" json:"amtSats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_lightning_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{6}
}

func (x *CreateInvoiceRequest) GetAmtSats() uint64 {
	if x != nil {
		return x.AmtSats
	}
	return 0
}

type CreateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       string                 `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_lightning_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*CreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{7}
}

func (x *CreateInvoiceResponse) GetInvoice() string {
	if x != nil {
		return x.Invoice
	}
	return ""
}

type PayInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       string                 `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayInvoiceRequest) Reset() {
	*x = PayInvoiceRequest{}
	mi := &file_lightning_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayInvoiceRequest) ProtoMessage() {}

func (x *PayInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayInvoiceRequest.ProtoReflect.Descriptor instead.
func (*PayInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{8}
}

func (x *PayInvoiceRequest) GetInvoice() string {
	if x != nil {
		return x.Invoice
	}
	return ""
}

type PayInvoiceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentPreimage []byte                 `protobuf:"bytes,2,opt,name=paymentPreimage,proto3" json:"paymentPreimage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayInvoiceResponse) Reset() {
	*x = PayInvoiceResponse{}
	mi := &file_lightning_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayInvoiceResponse) ProtoMessage() {}

func (x *PayInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayInvoiceResponse.ProtoReflect.Descriptor instead.
func (*PayInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{9}
}

func (x *PayInvoiceResponse) GetPaymentPreimage() []byte {
	if x != nil {
		return x.PaymentPreimage
	}
	return nil
}

type ChannelBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelBalanceRequest) Reset() {
	*x = ChannelBalanceRequest{}
	mi := &file_lightning_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelBalanceRequest) ProtoMessage() {}

func (x *ChannelBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelBalanceRequest.ProtoReflect.Descriptor instead.
func (*ChannelBalanceRequest) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{10}
}

type ChannelBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalanceSats   uint64                 `protobuf:"varint,1,opt,name=balanceSats,proto3" json:"balanceSats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelBalanceResponse) Reset() {
	*x = ChannelBalanceResponse{}
	mi := &file_lightning_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelBalanceResponse) ProtoMessage() {}

func (x *ChannelBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightning_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelBalanceResponse.ProtoReflect.Descriptor instead.
func (*ChannelBalanceResponse) Descriptor() ([]byte, []int) {
	return file_lightning_client_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelBalanceResponse) GetBalanceSats() uint64 {
	if x != nil {
		return x.BalanceSats
	}
	return 0
}

var File_lightning_client_proto protoreflect.FileDescriptor

const file_lightning_client_proto_rawDesc = "" +
	"\n" +
	"\x16lightning_client.proto\"\x0f\n" +
	"\rPubKeyRequest\"(\n" +
	"\x0ePubKeyResponse\x12\x16\n" +
	"\x06pubKey\x18\x01 \x01(\fR\x06pubKey\"T\n" +
	"\x12ConnectPeerRequest\x12\x16\n" +
	"\x06pubKey\x18\x01 \x01(\fR\x06pubKey\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"\x15\n" +
	"\x13ConnectPeerResponse\"P\n" +
	"\x12OpenChannelRequest\x12\x16\n" +
	"\x06pubKey\x18\x01 \x01(\fR\x06pubKey\x12\"\n" +
	"\flocalAmtSats\x18\x02 \x01(\x04R\flocalAmtSats\"k\n" +
	"\x13OpenChannelResponse\x12 \n" +
	"\vfundingTxId\x18\x01 \x01(\fR\vfundingTxId\x122\n" +
	"\x14fundingTxOutputIndex\x18\x02 \x01(\rR\x14fundingTxOutputIndex\"0\n" +
	"\x14CreateInvoiceRequest\x12\x18\n" +
	"\aamtSats\x18\x01 \x01(\x04R\aamtSats\"1\n" +
	"\x15CreateInvoiceResponse\x12\x18\n" +
	"\ainvoice\x18\x01 \x01(\tR\ainvoice\"-\n" +
	"\x11PayInvoiceRequest\x12\x18\n" +
	"\ainvoice\x18\x01 \x01(\tR\ainvoice\">\n" +
	"\x12PayInvoiceResponse\x12(\n" +
	"\x0fpaymentPreimage\x18\x02 \x01(\fR\x0fpaymentPreimage\"\x17\n" +
	"\x15ChannelBalanceRequest\":\n" +
	"\x16ChannelBalanceResponse\x12 \n" +
	"\vbalanceSats\x18\x01 \x01(\x04R\vbalanceSats2\xf0\x02\n" +
	"\tLightning\x12+\n" +
	"\x06PubKey\x12\x0e.PubKeyRequest\x1a\x0f.PubKeyResponse\"\x00\x12:\n" +
	"\vConnectPeer\x12\x13.ConnectPeerRequest\x1a\x14.ConnectPeerResponse\"\x00\x12:\n" +
	"\vOpenChannel\x12\x13.OpenChannelRequest\x1a\x14.OpenChannelResponse\"\x00\x12@\n" +
	"\rCreateInvoice\x12\x15.CreateInvoiceRequest\x1a\x16.CreateInvoiceResponse\"\x00\x127\n" +
	"\n" +
	"PayInvoice\x12\x12.PayInvoiceRequest\x1a\x13.PayInvoiceResponse\"\x00\x12C\n" +
	"\x0eChannelBalance\x12\x16.ChannelBalanceRequest\x1a\x17.ChannelBalanceResponse\"\x00b\x06proto3"

var (
	file_lightning_client_proto_rawDescOnce sync.Once
	file_lightning_client_proto_rawDescData []byte
)

func file_lightning_client_proto_rawDescGZIP() []byte {
	file_lightning_client_proto_rawDescOnce.Do(func() {
		file_lightning_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lightning_client_proto_rawDesc), len(file_lightning_client_proto_rawDesc)))
	})
	return file_lightning_client_proto_rawDescData
}

var file_lightning_client_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_lightning_client_proto_goTypes = []any{
	(*PubKeyRequest)(nil),          // 0: PubKeyRequest
	(*PubKeyResponse)(nil),         // 1: PubKeyResponse
	(*ConnectPeerRequest)(nil),     // 2: ConnectPeerRequest
	(*ConnectPeerResponse)(nil),    // 3: ConnectPeerResponse
	(*OpenChannelRequest)(nil),     // 4: OpenChannelRequest
	(*OpenChannelResponse)(nil),    // 5: OpenChannelResponse
	(*CreateInvoiceRequest)(nil),   // 6: CreateInvoiceRequest
	(*CreateInvoiceResponse)(nil),  // 7: CreateInvoiceResponse
	(*PayInvoiceRequest)(nil),      // 8: PayInvoiceRequest
	(*PayInvoiceResponse)(nil),     // 9: PayInvoiceResponse
	(*ChannelBalanceRequest)(nil),  // 10: ChannelBalanceRequest
	(*ChannelBalanceResponse)(nil), // 11: ChannelBalanceResponse
}
var file_lightning_client_proto_depIdxs = []int32{
	0,  // 0: Lightning.PubKey:input_type -> PubKeyRequest
	2,  // 1: Lightning.ConnectPeer:input_type -> ConnectPeerRequest
	4,  // 2: Lightning.OpenChannel:input_type -> OpenChannelRequest
	6,  // 3: Lightning.CreateInvoice:input_type -> CreateInvoiceRequest
	8,  // 4: Lightning.PayInvoice:input_type -> PayInvoiceRequest
	10, // 5: Lightning.ChannelBalance:input_type -> ChannelBalanceRequest
	1,  // 6: Lightning.PubKey:output_type -> PubKeyResponse
	3,  // 7: Lightning.ConnectPeer:output_type -> ConnectPeerResponse
	5,  // 8: Lightning.OpenChannel:output_type -> OpenChannelResponse
	7,  // 9: Lightning.CreateInvoice:output_type -> CreateInvoiceResponse
	9,  // 10: Lightning.PayInvoice:output_type -> PayInvoiceResponse
	11, // 11: Lightning.ChannelBalance:output_type -> ChannelBalanceResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_lightning_client_proto_init() }
func file_lightning_client_proto_init() {
	if File_lightning_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lightning_client_proto_rawDesc), len(file_lightning_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lightning_client_proto_goTypes,
		DependencyIndexes: file_lightning_client_proto_depIdxs,
		MessageInfos:      file_lightning_client_proto_msgTypes,
	}.Build()
	File_lightning_client_proto = out.File
	file_lightning_client_proto_goTypes = nil
	file_lightning_client_proto_depIdxs = nil
}
